image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Push $BITBUCKET_REPO_SLUG
            script:
              - IMAGE_NAME="$BITBUCKET_REPO_SLUG"
              - docker build . --file Dockerfile --tag "$IMAGE_NAME"
              - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
              - docker push "$IMAGE_NAME"
            services:
              - docker
