image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Push $BITBUCKET_REPO_SLUG
            script:
              - IMAGE_NAME="$BITBUCKET_REPO_SLUG"
              - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
              - docker build . --file Dockerfile --tag "$IMAGE_NAME"
              - docker push "$IMAGE_NAME"
            services:
              - docker
