on:
  push:
    branches:
      - latest
  workflow_dispatch:
  repository_dispatch:
    types:
      - latest
jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  dispatch:
    needs: build
    strategy:
      matrix:
        repo:
          - ${{ github.actor }}/cherry.docker
          - ${{ github.actor }}/libreoffice.docker
          - ${{ github.actor }}/pdf.docker
          - ${{ github.actor }}/pgadmin3.docker
          - ${{ github.actor }}/pgadmin.docker
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: latest
