name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ github.token }}
  INPUTS_DOCKERFILE: ${{ github.job }}.Dockerfile
  INPUTS_TAG: ${{ github.job }}
concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}/${{ github.job }}
jobs:
  alpine:
    env:
      INPUTS_TAG: latest
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 30
  dispatch:
    needs:
      - alpine
      - debian
      - ubuntu
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          INPUTS_CLIENT_PAYLOAD: '{"repository":${{ toJson(github.event.repository.name) }}}'
          INPUTS_EVENT_TYPE: latest
          INPUTS_REPOSITORY: ${{ github.repository_owner }}/${{ matrix.repo }}
        uses: rekgrpth/github-repository-dispatch-shell-action@v1
    strategy:
      matrix:
        repo:
          - cherry.docker
          - gar.docker
          - lib.docker
          - libreoffice.docker
          - pgadmin3.docker
          - pgadmin.docker
          - powa.docker
          - smtp.docker
