name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  build:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - uses: rekgrpth/docker-login-build-push-action@v1
  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/github-repository-dispatch-action@v1
        with:
          client-payload: '{"repository": ${{ toJson(github.event.repository.name) }}}'
          event-type: latest
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    strategy:
      matrix:
        repo:
          - cherry.docker
          - libreoffice.docker
          - pdf.docker
          - pgadmin3.docker
          - pgadmin.docker
