name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
  dispatch:
    needs: latest
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          INPUTS_CLIENT_PAYLOAD: '{"repository":${{ toJson(github.event.repository.name) }}}'
          INPUTS_EVENT_TYPE: latest
          INPUTS_REPOSITORY: ${{ github.repository_owner }}/${{ matrix.repo }}
        uses: rekgrpth/github-repository-dispatch-shell-action@v1
    strategy:
      matrix:
        repo:
          - cherry.docker
          - gar.docker
          - libreoffice.docker
          - pdf.docker
          - pgadmin3.docker
          - pgadmin.docker
          - powa.docker
          - smtp.docker
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: ubuntu
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: ubuntu
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: debian
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: debian
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/edge
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: edge
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: edge
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  b_3_14:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/3.14
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: 3.14
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: 3.14
        uses: rekgrpth/docker-login-build-push-shell-action@v1
  b_3_13:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/3.13
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_BRANCH: 3.13
        uses: rekgrpth/git-clone-shell-action@v1
      - env:
          INPUTS_TAG: 3.13
        uses: rekgrpth/docker-login-build-push-shell-action@v1
