name: Docker
on:
  push:
    branches:
      - latest
  repository_dispatch:
    types:
      - latest
  workflow_dispatch:
jobs:
  latest:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    name: ${{ github.event.client_payload.repository }} ${{ github.event_name }} ${{ github.event.branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  edge:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/edge
    env:
      DOCKER_FROM: alpine:edge
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_TAG: edge
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  debian:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/debian
    env:
      DOCKER_FROM: debian:stable-slim
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_DOCKERFILE: Dockerfile.debian
      INPUTS_TAG: debian
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  ubuntu:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/ubuntu
    env:
      DOCKER_FROM: ubuntu:rolling
      GITHUB_TOKEN: ${{ github.token }}
      INPUTS_DOCKERFILE: Dockerfile.debian
      INPUTS_TAG: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-shell-action@v1
      - uses: rekgrpth/docker-login-build-push-shell-action@v1
      - uses: rekgrpth/github-publish-action-shell-action@v1
    timeout-minutes: 20
  dispatch:
    needs:
      - debian
      - edge
      - latest
      - ubuntu
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          INPUTS_CLIENT_PAYLOAD: '{"repository":${{ toJson(github.event.repository.name) }}}'
          INPUTS_EVENT_TYPE: latest
          INPUTS_REPOSITORY: ${{ github.repository_owner }}/${{ matrix.repo }}
        uses: rekgrpth/github-repository-dispatch-shell-action@v1
    strategy:
      matrix:
        repo:
          - cherry.docker
          - gar.docker
          - lib.docker
          - libreoffice.docker
          - pgadmin3.docker
          - pgadmin.docker
          - powa.docker
          - smtp.docker
